package presentation;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

public class VistaGestionAlfabetos extends JFrame {

    CtrlPresentacion iCtrlPresentacion;
    private JButton buttonConsultarAlfabeto;
    private JButton buttonModificarAlfabeto;
    private JButton buttonEliminarAlfabeto;
    private JPanel panelContenidos;
    private JPanel panelBotones;
    private JLabel labelGestionAlfabetos;
    private JButton atrásButton;
    private JButton buttonCrearAlfabeto;


    public VistaGestionAlfabetos(CtrlPresentacion pCtrlPresentacion) {
        iCtrlPresentacion = pCtrlPresentacion;
        inicializarComponentes();
    }

    public void hacerVisible() {
        this.pack();
        this.setVisible(true);
    }

    public void hacerInvisible() {
        this.setVisible(false);
    }

    public void activar() {
        this.setEnabled(true);
    }

    public void desactivar() {
        this.setEnabled(false);
    }

    private void inicializarComponentes() {
        inicializar_frameVista();
        asignar_listenersComponentes();
    }

    private void inicializar_frameVista() {
        this.setTitle("Gestión de alfabetos");
        this.setMinimumSize(new Dimension(700, 500));
        this.setPreferredSize(this.getMinimumSize());
        this.setResizable(false);

        // Posicion y operaciones por defecto
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        // Add WindowListener to the frame
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                try {
                    performOperationBeforeExit();
                } catch (Exception ex) {
                    throw new RuntimeException(ex);
                }
            }
        });

        this.setContentPane(panelContenidos);
    }

    private void performOperationBeforeExit() throws Exception {
        int result = JOptionPane.showConfirmDialog(this, "Seguro que quieres salir?", "Confirmation",
                JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            try {
                iCtrlPresentacion.guardarDatos();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            dispose(); // Close the frame
            iCtrlPresentacion.cerrarPrograma();
        }
    }

    private void asignar_listenersComponentes() {
        atrásButton.addActionListener(
                new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent event) {
                        actionPerformed_atrásButton(event);
                    }
                });
    }

    void actionPerformed_atrásButton(ActionEvent event) {
        iCtrlPresentacion.syncVistaGestionAlfabetos_a_MenuPrincipal();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelContenidos = new JPanel();
        panelContenidos.setLayout(new GridBagLayout());
        final JPanel spacer1 = new JPanel();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.ipady = 30;
        panelContenidos.add(spacer1, gbc);
        panelBotones = new JPanel();
        panelBotones.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.BOTH;
        panelContenidos.add(panelBotones, gbc);
        buttonConsultarAlfabeto = new JButton();
        buttonConsultarAlfabeto.setMaximumSize(new Dimension(250, 60));
        buttonConsultarAlfabeto.setMinimumSize(new Dimension(250, 60));
        buttonConsultarAlfabeto.setPreferredSize(new Dimension(250, 60));
        buttonConsultarAlfabeto.setText("Consultar alfabetos");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        panelBotones.add(buttonConsultarAlfabeto, gbc);
        buttonModificarAlfabeto = new JButton();
        buttonModificarAlfabeto.setMaximumSize(new Dimension(250, 60));
        buttonModificarAlfabeto.setMinimumSize(new Dimension(250, 60));
        buttonModificarAlfabeto.setPreferredSize(new Dimension(250, 60));
        buttonModificarAlfabeto.setText("Modificar alfabeto");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        panelBotones.add(buttonModificarAlfabeto, gbc);
        buttonEliminarAlfabeto = new JButton();
        buttonEliminarAlfabeto.setMaximumSize(new Dimension(250, 60));
        buttonEliminarAlfabeto.setMinimumSize(new Dimension(250, 60));
        buttonEliminarAlfabeto.setPreferredSize(new Dimension(250, 60));
        buttonEliminarAlfabeto.setText("Eliminar alfabeto");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        panelBotones.add(buttonEliminarAlfabeto, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        panelBotones.add(spacer2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        panelBotones.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.VERTICAL;
        panelBotones.add(spacer4, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.VERTICAL;
        panelBotones.add(spacer5, gbc);
        atrásButton = new JButton();
        atrásButton.setActionCommand("Atras");
        atrásButton.setMaximumSize(new Dimension(50, 30));
        atrásButton.setMinimumSize(new Dimension(50, 30));
        atrásButton.setPreferredSize(new Dimension(50, 30));
        atrásButton.setText("Atrás");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.ipadx = 20;
        panelBotones.add(atrásButton, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 9;
        gbc.fill = GridBagConstraints.VERTICAL;
        panelBotones.add(spacer6, gbc);
        buttonCrearAlfabeto = new JButton();
        buttonCrearAlfabeto.setMaximumSize(new Dimension(250, 60));
        buttonCrearAlfabeto.setMinimumSize(new Dimension(250, 60));
        buttonCrearAlfabeto.setPreferredSize(new Dimension(250, 60));
        buttonCrearAlfabeto.setText("Crear nuevo alfabeto");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        panelBotones.add(buttonCrearAlfabeto, gbc);
        labelGestionAlfabetos = new JLabel();
        labelGestionAlfabetos.setText("Gestión de alfabetos");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        panelContenidos.add(labelGestionAlfabetos, gbc);
        final JPanel spacer7 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        panelContenidos.add(spacer7, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelContenidos;
    }

}
