package presentation;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

public class VistaBienvenida extends javax.swing.JFrame {
    private CtrlPresentacion iCtrlPresentacion;

    public VistaBienvenida(CtrlPresentacion pCtrlPresentacion) {
        iCtrlPresentacion = pCtrlPresentacion;
        initComponents();
        initOthers();
    }
    
    public void hacerVisible() {
        this.pack();
        this.setVisible(true);
    }

    public void hacerInvisible() {
        this.setVisible(false);
    }

    public void activar() {
        this.setEnabled(true);
    }

    public void desactivar() {
        this.setEnabled(false);
    }

    // Method to perform an operation before exiting
    private void performOperationBeforeExit() throws Exception {
        // Your operation logic goes here
        int result = JOptionPane.showConfirmDialog(this, "Seguro que quieres salir?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            // Perform cleanup or other necessary operations before exiting
            try {
                iCtrlPresentacion.guardarDatos();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            this.dispose(); // Close the frame
            iCtrlPresentacion.cerrarPrograma();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenidos = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        labelLogo = new javax.swing.JLabel();
        panelInput = new javax.swing.JPanel();
        fieldUsuario = new javax.swing.JTextField();
        labelUsuario = new javax.swing.JLabel();
        labelContrasena = new javax.swing.JLabel();
        fieldContrasena = new javax.swing.JPasswordField();
        btnIniciarSesion = new javax.swing.JButton();
        labelRegistrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("KeyboardCraft");
        setMinimumSize(new java.awt.Dimension(375, 550));
        setSize(new java.awt.Dimension(375, 550));

        panelContenidos.setBackground(new java.awt.Color(249, 247, 243));
        panelContenidos.setMinimumSize(new java.awt.Dimension(375, 550));
        panelContenidos.setPreferredSize(new java.awt.Dimension(375, 550));

        labelTitulo.setFont(new java.awt.Font("URW Gothic L", 1, 24)); // NOI18N
        labelTitulo.setText("KeyboardCraft");

        panelInput.setBackground(new java.awt.Color(249, 247, 243));

        fieldUsuario.setColumns(8);
        fieldUsuario.setFont(new java.awt.Font("URW Gothic L", 0, 15)); // NOI18N
        fieldUsuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        labelUsuario.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        labelUsuario.setText("Usuario:");

        labelContrasena.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        labelContrasena.setText("Contraseña:");

        fieldContrasena.setColumns(8);
        fieldContrasena.setFont(new java.awt.Font("URW Gothic L", 0, 15)); // NOI18N
        fieldContrasena.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldContrasena.setToolTipText("");

        btnIniciarSesion.setBackground(new java.awt.Color(94, 211, 192));
        btnIniciarSesion.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion.setText("Iniciar Sesión");
        btnIniciarSesion.setMinimumSize(new java.awt.Dimension(150, 50));
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        labelRegistrar.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        labelRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRegistrar.setText("<html><center>¿Aún no tienes cuenta?<br />Regístrate</center></html>");
        labelRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRegistrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelRegistrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelInputLayout = new javax.swing.GroupLayout(panelInput);
        panelInput.setLayout(panelInputLayout);
        panelInputLayout.setHorizontalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputLayout.createSequentialGroup()
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(fieldContrasena)
                    .addComponent(fieldUsuario))
                .addGap(4, 4, 4))
            .addComponent(btnIniciarSesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelRegistrar))
        );
        panelInputLayout.setVerticalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(fieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(fieldContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelInputLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {fieldContrasena, fieldUsuario});

        javax.swing.GroupLayout panelContenidosLayout = new javax.swing.GroupLayout(panelContenidos);
        panelContenidos.setLayout(panelContenidosLayout);
        panelContenidosLayout.setHorizontalGroup(
            panelContenidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenidosLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(panelContenidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(panelInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTitulo))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        panelContenidosLayout.setVerticalGroup(
            panelContenidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenidosLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
        String user = fieldUsuario.getText();
        char[] passwordChars = fieldContrasena.getPassword();
        String password = new String(passwordChars);
        try {
            iCtrlPresentacion.iniciarSesion(user, password);
            limpiarCamposInput();
            iCtrlPresentacion.syncVistaBienvenida_a_MenuPrincipal();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }                                                

    private void labelRegistrarMouseClicked(java.awt.event.MouseEvent evt) {                                            
        // TODO add your handling code here:
        limpiarCamposInput();
        iCtrlPresentacion.syncVistaBienvenida_a_CrearCuenta();
    }                                           

    private void labelRegistrarMouseEntered(java.awt.event.MouseEvent evt) {                                            
        // TODO add your handling code here:
        labelRegistrar.setForeground(Color.BLUE); // Change text color on hover
    }                                           

    private void labelRegistrarMouseExited(java.awt.event.MouseEvent evt) {                                           
        // TODO add your handling code here:
        labelRegistrar.setForeground(Color.BLACK); // Restore initial text color on exit
    } 

    private void initOthers() {
        setLocationRelativeTo(null); // Center the window on the screen

        // Add a window listener to intercept the window-closing event
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                try {
                    performOperationBeforeExit();
                } catch (Exception ex) {
                    throw new RuntimeException(ex);
                }
            }
        });
    }

    private void limpiarCamposInput() {
        fieldUsuario.setText("");
        fieldContrasena.setText("");
        fieldUsuario.revalidate();
        fieldUsuario.repaint();
        fieldContrasena.revalidate();
        fieldContrasena.repaint();
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JPasswordField fieldContrasena;
    private javax.swing.JTextField fieldUsuario;
    private javax.swing.JLabel labelContrasena;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelRegistrar;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JPanel panelContenidos;
    private javax.swing.JPanel panelInput;
    // End of variables declaration   
    
}
