package presentation;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

public class VistaGestionTeclados extends JFrame {

    CtrlPresentacion iCtrlPresentacion;
    private JButton buttonConsultarTeclados;
    private JButton buttonModificarTeclado;
    private JButton buttonEliminarTeclado;
    private JPanel panelContenidos;
    private JPanel panelBotones;
    private JLabel labelGestionTeclados;
    private JButton buttonVolver;
    private JButton buttonCrearTeclado;

    public VistaGestionTeclados(CtrlPresentacion pCtrlPresentacion) {
        iCtrlPresentacion = pCtrlPresentacion;
        inicializarComponentes();
    }

    public void hacerVisible() {
        this.pack();
        this.setVisible(true);
    }

    public void hacerInvisible() {
        this.setVisible(false);
    }

    public void activar() {
        this.setEnabled(true);
    }

    public void desactivar() {
        this.setEnabled(false);
    }

    private void inicializarComponentes() {
        inicializar_frameVista();
        asignar_listenersComponentes();
    }

    private void inicializar_frameVista() {
        this.setTitle("Gestión de alfabetos");
        this.setMinimumSize(new Dimension(700, 500));
        this.setPreferredSize(this.getMinimumSize());
        this.setResizable(false);

        // Posicion y operaciones por defecto
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        // Add WindowListener to the frame
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                try {
                    performOperationBeforeExit();
                } catch (Exception ex) {
                    throw new RuntimeException(ex);
                }
            }
        });

        this.setContentPane(panelContenidos);
    }

    private void performOperationBeforeExit() throws Exception {
        int result = JOptionPane.showConfirmDialog(this, "Seguro que quieres salir?", "Confirmation",
                JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            try {
                iCtrlPresentacion.guardarDatos();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            dispose(); // Close the frame
            iCtrlPresentacion.cerrarPrograma();
        }
    }

    private void asignar_listenersComponentes() {
        buttonVolver.addActionListener(
                new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent event) {
                        actionPerformed_buttonVolver(event);
                    }
                });
        buttonCrearTeclado.addActionListener(
                new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent event) {
                        actionPerformed_buttonCrearTeclado(event);
                    }
                });
        buttonConsultarTeclados.addActionListener(
                new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent event) {
                        actionPerformed_buttonConsultarTeclado(event);
                    }
                });
        buttonModificarTeclado.addActionListener(
                new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent event) {

                    }
                });
        buttonEliminarTeclado.addActionListener(
                new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent event) {
                        actionPerformed_buttonEliminarTeclado(event);
                    }
                });
    }

    void actionPerformed_buttonVolver(ActionEvent event) {
        iCtrlPresentacion.syncVistaGestionTeclados_a_MenuPrincipal();
    }

    void actionPerformed_buttonCrearTeclado(ActionEvent event) {

    }

    void actionPerformed_buttonConsultarTeclado(ActionEvent event) {

    }

    void actionPerformed_buttonEliminarTeclado(ActionEvent event) {

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelContenidos = new JPanel();
        panelContenidos.setLayout(new GridBagLayout());
        final JPanel spacer1 = new JPanel();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.ipady = 30;
        panelContenidos.add(spacer1, gbc);
        panelBotones = new JPanel();
        panelBotones.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.BOTH;
        panelContenidos.add(panelBotones, gbc);
        buttonConsultarTeclados = new JButton();
        buttonConsultarTeclados.setMaximumSize(new Dimension(250, 60));
        buttonConsultarTeclados.setMinimumSize(new Dimension(250, 60));
        buttonConsultarTeclados.setPreferredSize(new Dimension(250, 60));
        buttonConsultarTeclados.setText("Consultar teclados");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        panelBotones.add(buttonConsultarTeclados, gbc);
        buttonModificarTeclado = new JButton();
        buttonModificarTeclado.setMaximumSize(new Dimension(250, 60));
        buttonModificarTeclado.setMinimumSize(new Dimension(250, 60));
        buttonModificarTeclado.setPreferredSize(new Dimension(250, 60));
        buttonModificarTeclado.setText("Modificar teclado");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        panelBotones.add(buttonModificarTeclado, gbc);
        buttonEliminarTeclado = new JButton();
        buttonEliminarTeclado.setMaximumSize(new Dimension(250, 60));
        buttonEliminarTeclado.setMinimumSize(new Dimension(250, 60));
        buttonEliminarTeclado.setPreferredSize(new Dimension(250, 60));
        buttonEliminarTeclado.setText("Eliminar teclado");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        panelBotones.add(buttonEliminarTeclado, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        panelBotones.add(spacer2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        panelBotones.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.VERTICAL;
        panelBotones.add(spacer4, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.VERTICAL;
        panelBotones.add(spacer5, gbc);
        buttonVolver = new JButton();
        buttonVolver.setActionCommand("Atras");
        buttonVolver.setMaximumSize(new Dimension(50, 30));
        buttonVolver.setMinimumSize(new Dimension(50, 30));
        buttonVolver.setPreferredSize(new Dimension(50, 30));
        buttonVolver.setText("Volver");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.ipadx = 20;
        panelBotones.add(buttonVolver, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 9;
        gbc.fill = GridBagConstraints.VERTICAL;
        panelBotones.add(spacer6, gbc);
        buttonCrearTeclado = new JButton();
        buttonCrearTeclado.setMaximumSize(new Dimension(250, 60));
        buttonCrearTeclado.setMinimumSize(new Dimension(250, 60));
        buttonCrearTeclado.setPreferredSize(new Dimension(250, 60));
        buttonCrearTeclado.setText("Crear nuevo teclado");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        panelBotones.add(buttonCrearTeclado, gbc);
        labelGestionTeclados = new JLabel();
        labelGestionTeclados.setText("Gestión de teclados");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        panelContenidos.add(labelGestionTeclados, gbc);
        final JPanel spacer7 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        panelContenidos.add(spacer7, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelContenidos;
    }

}
