package presentation;

import exceptions.ContrasenaNoValidaExcepcion;
import exceptions.EscrituraIncorrectaFicheroExcepcion;
import exceptions.NombreUsuarioNoValidoExcepcion;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class VistaMenuPrincipal extends JFrame {
    CtrlPresentacion iCtrlPresentacion;
    private JPanel panelContenidos;
    private JButton btnGestionarTeclados;
    private JButton btnGestionarAlfabetos;
    private JButton btnGestionarPerfil;
    private JButton btnLogOut;
    private JPanel panelBotones;
    private JLabel labelTitulo;

    public VistaMenuPrincipal(CtrlPresentacion pCtrlPresentacion) {
        iCtrlPresentacion = pCtrlPresentacion;
        inicializarComponentes();
    }

    public void hacerVisible() {
        this.pack();
        this.setVisible(true);
    }

    public void hacerInvisible() {
        this.setVisible(false);
    }

    public void activar() {
        this.setEnabled(true);
    }

    public void desactivar() {
        this.setEnabled(false);
    }

    private void inicializarComponentes() {
        inicializar_frameVista();
        asignar_listenersComponentes();
    }

    private void inicializar_frameVista() {
        this.setTitle("Generador de teclados");
        this.setMinimumSize(new Dimension(600, 450));
        this.setPreferredSize(this.getMinimumSize());
        this.setResizable(false);

        // Posicion y operaciones por defecto
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        // Add WindowListener to the frame
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                try {
                    performOperationBeforeExit();
                } catch (Exception ex) {
                    throw new RuntimeException(ex);
                }
            }
        });

        this.setContentPane(panelContenidos);
    }

    private void performOperationBeforeExit() throws Exception {
        int result = JOptionPane.showConfirmDialog(this, "Seguro que quieres salir?", "Confirmation",
                JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            try {
                iCtrlPresentacion.guardarDatos();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            dispose(); // Close the frame
            iCtrlPresentacion.cerrarPrograma();
        }
    }

    private void asignar_listenersComponentes() {
        // Listeners para los botones
        btnGestionarAlfabetos.addActionListener(
                new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent event) {
                        actionPerformed_btnGestionarAlfabetos(event);
                    }
                });
        btnGestionarTeclados.addActionListener(
                new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent event) {
                        actionPerformed_btnGestionarTeclados(event);
                    }
                });
        btnGestionarPerfil.addActionListener(
                new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent event) {
                        actionPerformed_btnGestionarPerfil(event);
                    }
                });
        btnLogOut.addActionListener(
                new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent event) {
                        actionPerformed_btnLogout(event);
                    }
                });

    }

    public void actionPerformed_btnGestionarAlfabetos(ActionEvent event) {
        iCtrlPresentacion.syncVistaMenuPrincipal_a_GestionAlfabetos();
    }

    public void actionPerformed_btnGestionarTeclados(ActionEvent event) {
        iCtrlPresentacion.syncVistaMenuPrincipal_a_GestionTeclados();
    }

    public void actionPerformed_btnGestionarPerfil(ActionEvent event) {
        iCtrlPresentacion.syncVistaMenuPrincipal_a_GestionPerfil();
    }

    public void actionPerformed_btnLogout(ActionEvent event) {
        try {
            iCtrlPresentacion.cerrarSesion();
            iCtrlPresentacion.syncVistaMenuPrincipal_a_Bienvenida();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelContenidos = new JPanel();
        panelContenidos.setLayout(new GridBagLayout());
        panelBotones = new JPanel();
        panelBotones.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panelContenidos.add(panelBotones, gbc);
        btnGestionarTeclados = new JButton();
        btnGestionarTeclados.setPreferredSize(new Dimension(250, 60));
        btnGestionarTeclados.setText("Gestionar teclados");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        panelBotones.add(btnGestionarTeclados, gbc);
        btnGestionarAlfabetos = new JButton();
        btnGestionarAlfabetos.setPreferredSize(new Dimension(250, 60));
        btnGestionarAlfabetos.setText("Gestionar alfabetos");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        panelBotones.add(btnGestionarAlfabetos, gbc);
        btnGestionarPerfil = new JButton();
        btnGestionarPerfil.setHorizontalAlignment(0);
        btnGestionarPerfil.setPreferredSize(new Dimension(250, 60));
        btnGestionarPerfil.setText("Gestionar perfil");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        panelBotones.add(btnGestionarPerfil, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        panelBotones.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        panelBotones.add(spacer2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        panelContenidos.add(spacer3, gbc);
        labelTitulo = new JLabel();
        labelTitulo.setHorizontalAlignment(0);
        labelTitulo.setHorizontalTextPosition(0);
        labelTitulo.setText("Menú Principal");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        panelContenidos.add(labelTitulo, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        gbc.ipady = 30;
        panelContenidos.add(spacer4, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        panelContenidos.add(spacer5, gbc);
        btnLogOut = new JButton();
        btnLogOut.setPreferredSize(new Dimension(82, 30));
        btnLogOut.setText("Log out");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.weightx = 1.0;
        panelContenidos.add(btnLogOut, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelContenidos;
    }

}
