package presentation;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;
import java.util.*;

/**
 *
 * @author jianingxu
 */
public class VistaGestionTeclados extends javax.swing.JFrame {
    private CtrlPresentacion iCtrlPresentacion;
    private boolean userSelection = true;
    
    /**
     * Creates new form VistaGestionTeclados
     */
    public VistaGestionTeclados(CtrlPresentacion pCtrlPresentacion) {
        iCtrlPresentacion = pCtrlPresentacion;
        initComponents();
        inicializar_frameVista();
        resetCardCrearTeclado();
        mostrarCardCrearTeclado();
    }
    
    public void hacerVisible() {
        pack();
        setVisible(true);
        resetCardCrearTeclado();
        mostrarCardCrearTeclado();
    }

    public void hacerInvisible() {
        setVisible(false);
    }

    public void activar() {
        setEnabled(true);
    }

    public void desactivar() {
        setEnabled(false);
    }
    
    private void inicializar_frameVista() {
        setResizable(false);

        // Posicion y operaciones por defecto
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        // Add WindowListener to the frame
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                try {
                    performOperationBeforeExit();
                } catch (Exception ex) {
                    throw new RuntimeException(ex);
                }
            }
        });
    }

    private void performOperationBeforeExit() throws Exception {
        int result = JOptionPane.showConfirmDialog(this, "Seguro que quieres salir?", "Confirmation",
                JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            try {
                iCtrlPresentacion.guardarDatos();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            dispose(); // Close the frame
            iCtrlPresentacion.cerrarPrograma();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        panelCard = new javax.swing.JPanel();
        panelModificar = new javax.swing.JPanel();
        labelTeclado = new javax.swing.JLabel();
        comboboxTeclado = new javax.swing.JComboBox<>();
        panelTeclas = new javax.swing.JPanel();
        btnEliminarTeclado = new javax.swing.JButton();
        fieldCaracter2 = new javax.swing.JTextField();
        fieldCaracter1 = new javax.swing.JTextField();
        labelCaracter1 = new javax.swing.JLabel();
        labelCaracter2 = new javax.swing.JLabel();
        btnIntercambiarTeclas = new javax.swing.JButton();
        panelCrear = new javax.swing.JPanel();
        labelNombreTeclado = new javax.swing.JLabel();
        fieldNombreTeclado = new javax.swing.JTextField();
        labelAlfabeto = new javax.swing.JLabel();
        comboboxAlfabeto = new javax.swing.JComboBox<>();
        labelTexto = new javax.swing.JLabel();
        labelPalabrasConFrecuencia = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaPalabrasConFrecuencia = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaTexto = new javax.swing.JTextArea();
        btnCrearTeclado = new javax.swing.JButton();
        labelAlgoritmo = new javax.swing.JLabel();
        comboboxAlgoritmo = new javax.swing.JComboBox<>();
        menubarAcciones = new javax.swing.JMenuBar();
        menuCrear = new javax.swing.JMenu();
        menuModificar = new javax.swing.JMenu();
        menuVolver = new javax.swing.JMenu();

        jLabel2.setText("Intercambiar teclas:");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("KeyboardCraft - Gestión de teclados");
        setMinimumSize(new java.awt.Dimension(500, 400));

        labelTitulo.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        labelTitulo.setText("Gestión de teclados");

        panelCard.setLayout(new java.awt.CardLayout());

        labelTeclado.setText("Teclado:");

        comboboxTeclado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxTecladoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTeclasLayout = new javax.swing.GroupLayout(panelTeclas);
        panelTeclas.setLayout(panelTeclasLayout);
        panelTeclasLayout.setHorizontalGroup(
            panelTeclasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );
        panelTeclasLayout.setVerticalGroup(
            panelTeclasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
        );

        btnEliminarTeclado.setText("Eliminar teclado");
        btnEliminarTeclado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTecladoActionPerformed(evt);
            }
        });

        fieldCaracter2.setColumns(2);

        fieldCaracter1.setColumns(2);

        labelCaracter1.setText("Caracter 1:");

        labelCaracter2.setText("Caracter 2:");

        btnIntercambiarTeclas.setText("Intercambiar posicion");
        btnIntercambiarTeclas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntercambiarTeclasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelModificarLayout = new javax.swing.GroupLayout(panelModificar);
        panelModificar.setLayout(panelModificarLayout);
        panelModificarLayout.setHorizontalGroup(
            panelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(panelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModificarLayout.createSequentialGroup()
                        .addComponent(labelTeclado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboboxTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(235, 235, 235))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModificarLayout.createSequentialGroup()
                        .addComponent(panelTeclas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModificarLayout.createSequentialGroup()
                        .addGroup(panelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnIntercambiarTeclas)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelModificarLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(panelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCaracter2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelCaracter1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldCaracter2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldCaracter1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(57, 57, 57)
                        .addComponent(btnEliminarTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157))))
        );
        panelModificarLayout.setVerticalGroup(
            panelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTeclado)
                    .addComponent(comboboxTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTeclas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldCaracter1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCaracter1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCaracter2)
                    .addComponent(fieldCaracter2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIntercambiarTeclas)
                    .addComponent(btnEliminarTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        panelCard.add(panelModificar, "cardModificar");
        panelModificar.getAccessibleContext().setAccessibleName("");
        panelModificar.getAccessibleContext().setAccessibleDescription("");

        labelNombreTeclado.setText("Nombre del teclado:");

        fieldNombreTeclado.setColumns(10);

        labelAlfabeto.setText("Alfabeto a utilizar:");

        comboboxAlfabeto.setMaximumRowCount(10);

        labelTexto.setText("Texto:");

        labelPalabrasConFrecuencia.setText("Lista de palabras con frecuencia:");

        areaPalabrasConFrecuencia.setColumns(20);
        areaPalabrasConFrecuencia.setRows(5);
        jScrollPane1.setViewportView(areaPalabrasConFrecuencia);

        areaTexto.setColumns(20);
        areaTexto.setRows(5);
        jScrollPane2.setViewportView(areaTexto);

        btnCrearTeclado.setText("Crear teclado");
        btnCrearTeclado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearTecladoActionPerformed(evt);
            }
        });

        labelAlgoritmo.setText("Algoritmo a utilizar:");

        comboboxAlgoritmo.setMaximumRowCount(10);

        javax.swing.GroupLayout panelCrearLayout = new javax.swing.GroupLayout(panelCrear);
        panelCrear.setLayout(panelCrearLayout);
        panelCrearLayout.setHorizontalGroup(
            panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearLayout.createSequentialGroup()
                .addContainerGap(226, Short.MAX_VALUE)
                .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCrearLayout.createSequentialGroup()
                        .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCrearLayout.createSequentialGroup()
                                .addComponent(labelAlgoritmo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboboxAlgoritmo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane2)
                                .addComponent(jScrollPane1)
                                .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelPalabrasConFrecuencia)
                                    .addComponent(labelTexto)
                                    .addGroup(panelCrearLayout.createSequentialGroup()
                                        .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelNombreTeclado)
                                            .addComponent(labelAlfabeto))
                                        .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(panelCrearLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(fieldNombreTeclado))
                                            .addGroup(panelCrearLayout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(comboboxAlfabeto, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(207, 207, 207))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCrearLayout.createSequentialGroup()
                        .addComponent(btnCrearTeclado)
                        .addGap(283, 283, 283))))
        );
        panelCrearLayout.setVerticalGroup(
            panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearLayout.createSequentialGroup()
                .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombreTeclado)
                    .addComponent(fieldNombreTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAlfabeto)
                    .addComponent(comboboxAlfabeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAlgoritmo)
                    .addComponent(comboboxAlgoritmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelTexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPalabrasConFrecuencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCrearTeclado)
                .addContainerGap())
        );

        panelCard.add(panelCrear, "cardCrear");

        menuCrear.setText("Crear teclado");
        menuCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCrearMouseClicked(evt);
            }
        });
        menubarAcciones.add(menuCrear);

        menuModificar.setText("Modificar teclado");
        menuModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuModificarMouseClicked(evt);
            }
        });
        menubarAcciones.add(menuModificar);

        menuVolver.setText("Ir a menú principal");
        menuVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuVolverMouseClicked(evt);
            }
        });
        menubarAcciones.add(menuVolver);

        setJMenuBar(menubarAcciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTitulo)
                .addGap(275, 275, 275))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void btnEliminarTecladoActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        String nombreTeclado = (String) comboboxTeclado.getSelectedItem();
        try {
            iCtrlPresentacion.eliminarTeclado(nombreTeclado);
            actualizarNombreTecladosComboBox();
            panelTeclas.removeAll();
            fieldCaracter1.setText("");
            fieldCaracter2.setText("");
            JOptionPane.showMessageDialog(this, "¡Se ha eliminado el teclado " + nombreTeclado + " con éxito!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }                                                  

    private void btnIntercambiarTeclasActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
    }                                                     

    private void btnCrearTecladoActionPerformed(java.awt.event.ActionEvent evt) {                                                
        String nombreTeclado = fieldNombreTeclado.getText();
        String nombreAlfabeto = (String) comboboxAlfabeto.getSelectedItem();
        String nombreAlgoritmo = (String) comboboxAlgoritmo.getSelectedItem();
        String texto = areaTexto.getText();
        String palabrasConFrecuencia = areaPalabrasConFrecuencia.getText();
        try {
            iCtrlPresentacion.crearTeclado(nombreTeclado, nombreAlfabeto, texto, palabrasConFrecuencia, nombreAlgoritmo);
            resetCardCrearTeclado();
            JOptionPane.showMessageDialog(this, "¡Se ha creado el teclado " + nombreTeclado + " con éxito!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }                                               

    private void menuModificarMouseClicked(java.awt.event.MouseEvent evt) {                                           
        resetCardModificarTeclado();
        mostrarCardModificarTeclado();
    }                                          

    private void menuCrearMouseClicked(java.awt.event.MouseEvent evt) {                                       
        resetCardCrearTeclado();
        mostrarCardCrearTeclado();
    }                                      

    private void menuVolverMouseClicked(java.awt.event.MouseEvent evt) {                                        
        iCtrlPresentacion.syncVistaGestionTeclados_a_MenuPrincipal();
    }                                       

    private void comboboxTecladoActionPerformed(java.awt.event.ActionEvent evt) {                                                
        if (!userSelection) return;
        String nombreTeclado = (String) comboboxTeclado.getSelectedItem();
        try {
            Character[][] distribucion = iCtrlPresentacion.getDistribucionTeclado(nombreTeclado);
            int rows = distribucion.length;
            panelTeclas.removeAll();
            panelTeclas.setLayout(new GridLayout(rows, distribucion[0].length));
            for (int i = 0; i < rows; ++i) {
                int cols = distribucion[i].length;
                for (int j = 0; j < cols; ++j) {
                    JButton button = new JButton(distribucion[i][j].toString());
                    button.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            if (fieldCaracter1.getText().isEmpty()) {
                                fieldCaracter1.setText(button.getText());
                            } else if (fieldCaracter2.getText().isEmpty()) {
                                fieldCaracter2.setText(button.getText());
                            } else {
                                fieldCaracter1.setText(button.getText());
                                fieldCaracter2.setText("");
                            }
                        }
                    });
                    panelTeclas.add(button);
                }
            }
            panelTeclas.revalidate();
            panelTeclas.repaint();
            fieldCaracter1.setText("");
            fieldCaracter2.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }                                               

    private void mostrarCardCrearTeclado() {
        CardLayout cardLayout = (CardLayout)(panelCard.getLayout());
        cardLayout.show(panelCard, "cardCrear");
    }
    
    private void mostrarCardModificarTeclado() {
        CardLayout cardLayout = (CardLayout)(panelCard.getLayout());
        cardLayout.show(panelCard, "cardModificar");
    }
    
    private void actualizarNombreAlfabetosComboBox() {
        comboboxAlfabeto.removeAllItems();
        ArrayList<String> nombreAlfabetos = iCtrlPresentacion.getNombreAlfabetos();
        for (String nombreAlfabeto : nombreAlfabetos) {
            comboboxAlfabeto.addItem(nombreAlfabeto);
        }
        comboboxAlfabeto.setSelectedIndex(-1);
    }
    
    private void actualizarNombreTecladosComboBox() {
        userSelection = false;
        comboboxTeclado.removeAllItems();
        ArrayList<String> nombreTeclados = iCtrlPresentacion.getNombreTeclados();
        for (String nombreTeclado : nombreTeclados) {
            comboboxTeclado.addItem(nombreTeclado);
        }
        comboboxTeclado.setSelectedIndex(-1);
        userSelection = true;
    }
    
    private void actualizarNombreAlgoritmosComboBox() {
        comboboxAlgoritmo.removeAllItems();
        ArrayList<String> nombreAlgoritmos = iCtrlPresentacion.getNombreAlgoritmos();
        for (String nombreAlgoritmo : nombreAlgoritmos) {
            comboboxAlgoritmo.addItem(nombreAlgoritmo);
        }
        comboboxAlgoritmo.setSelectedIndex(-1);
    }
    
    private void resetCardCrearTeclado() {
        actualizarNombreAlfabetosComboBox();
        actualizarNombreAlgoritmosComboBox();
        fieldNombreTeclado.setText("");
        areaTexto.setText("");
        areaPalabrasConFrecuencia.setText("");
    }

    private void resetCardModificarTeclado() {
        actualizarNombreTecladosComboBox();
        fieldCaracter1.setText("");
        fieldCaracter2.setText("");
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextArea areaPalabrasConFrecuencia;
    private javax.swing.JTextArea areaTexto;
    private javax.swing.JButton btnCrearTeclado;
    private javax.swing.JButton btnEliminarTeclado;
    private javax.swing.JButton btnIntercambiarTeclas;
    private javax.swing.JComboBox<String> comboboxAlfabeto;
    private javax.swing.JComboBox<String> comboboxAlgoritmo;
    private javax.swing.JComboBox<String> comboboxTeclado;
    private javax.swing.JTextField fieldCaracter1;
    private javax.swing.JTextField fieldCaracter2;
    private javax.swing.JTextField fieldNombreTeclado;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelAlfabeto;
    private javax.swing.JLabel labelAlgoritmo;
    private javax.swing.JLabel labelCaracter1;
    private javax.swing.JLabel labelCaracter2;
    private javax.swing.JLabel labelNombreTeclado;
    private javax.swing.JLabel labelPalabrasConFrecuencia;
    private javax.swing.JLabel labelTeclado;
    private javax.swing.JLabel labelTexto;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JMenu menuCrear;
    private javax.swing.JMenu menuModificar;
    private javax.swing.JMenu menuVolver;
    private javax.swing.JMenuBar menubarAcciones;
    private javax.swing.JPanel panelCard;
    private javax.swing.JPanel panelCrear;
    private javax.swing.JPanel panelModificar;
    private javax.swing.JPanel panelTeclas;
    // End of variables declaration                   
}
